### ISSUE TITLE
Build error : 

### ISSUE THREAD

**Issue by hodaka0124** [gfx/Android-Helium#26]
OS: Windows10
IDE: Android Studio 1.4.1
commit 6a2f31c

Mac OSXだとビルドから実行まで出来るのですが、Windowsだと実行が出来ません。
Windows7でも試してみたのですが下記と同じエラーが出ました。

Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> cannot find android\databinding\DataBinderMapper$InnerBrLookup: android.databinding.DataBinderMapper$InnerBrLookup found in android\databinding\DataBinderMapper$InnerBrLookup.class

android-power-assertがwindowsだと動作させる事が出来ません。

**Comment by hodaka0124** [comment]
android-power-assertは何故OSに依存しますか？ご教授いただければ幸いです。

**Comment by gfx** [comment]
DataBindingをアップデートしました。もう一度試していただけますか？

**Comment by gfx** [comment]
だいぶ状況が変わったのでcloseします。
