### ISSUE TITLE
Will this appli show my favorite hatebu later ?

### ISSUE THREAD

**Issue by suzukaze** [gfx/Android-Helium#6]
[HBFav2](https://github.com/naoya/HBFav2) shows bookmarks of following users.

Will this appli show my favorite hatebu (bookmarks of following users) later ?

**Comment by gfx** [comment]
Yes! HBFav2 is the very original idea of Helium; I already uses this app every day and I want get my own favorite entries. However, I have no plan to post Hatebu entries for a while; I uses the official Hatebu app to do so.

**Comment by suzukaze** [comment]
Thank you. There is the official Hatebu app that show my own favarite hatebu.
